CLASS zcl_demo_flight DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    INTERFACES if_amdp_marker_hdb .

    CLASS-METHODS :get_flights for TABLE FUNCTION ZCDS_TABLE_FUNC.

  PROTECTED SECTION.

  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_DEMO_FLIGHT IMPLEMENTATION.


METHOD get_flights BY DATABASE FUNCTION FOR HDB LANGUAGE SQLSCRIPT
                    USING /DMO/FLIGHT .

RETURN SELECT * From  "/DMO/FLIGHT"
       where carrier_id = :carrier;


ENDMETHOD.
ENDCLASS.
